def load(pygame):
    pygame.init()  
    screen = pygame.display.set_mode((640, 480))  
    tuti_chip=pygame.image.load("img/tuti.png")
    kusa_chip=pygame.image.load("img/kusa.png")
    kawa_chip=pygame.image.load("img/kawa.png")
    iwa_chip=pygame.image.load("img/iwa.png")
    mizu_chip=pygame.image.load("img/mizu.png")
    bridge_chip=pygame.image.load("img/bridge.png")
    hashi_chip=pygame.image.load("img/hashi.png")
    bridge_chip2=pygame.image.load("img/bridge2.png")
    otakara_chip=pygame.image.load("img/otakara.png")
    otakaraake_chip=pygame.image.load("img/otakara_ake.png")
    kareki_chip=pygame.image.load("img/kareki.png")
    kannbann_chip=pygame.image.load("img/Kannbann.png")
    kawa_half=pygame.image.load("img/kawa_half.png")
    tuti_chip=pygame.transform.scale(tuti_chip,(32,32))
    kusa_chip=pygame.transform.scale(kusa_chip,(32,32))
    kawa_chip=pygame.transform.scale(kawa_chip,(32,32))
    iwa_chip=pygame.transform.scale(iwa_chip,(32,32))
    mizu_chip=pygame.transform.scale(mizu_chip,(32,32))
    bridge_chip=pygame.transform.scale(bridge_chip,(34,40))
    hashi_chip=pygame.transform.scale(hashi_chip,(32,32))
    bridge_chip=pygame.transform.scale(bridge_chip,(64,92))
    otakara_chip=pygame.transform.scale(otakara_chip,(32,32))
    otakaraake_chip=pygame.transform.scale(otakaraake_chip,(32,32))
    kareki_chip=pygame.transform.scale2x(kareki_chip)
    kannbann_chip=pygame.transform.scale2x(kannbann_chip)